// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;

/// Replace with your project values from Firebase Console, or run: dart pub global run flutterfire_cli:flutterfire configure
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    return web;
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDemoKeyForWeb',
    appId: '1:123456789:web:abcd1234efgh5678',
    messagingSenderId: '123456789',
    projectId: 'learnturn-7e707',
    authDomain: 'learnturn-7e707.firebaseapp.com',
    storageBucket: 'learnturn-7e707.appspot.com',
    measurementId: 'G-DEMO1234567',
  );
}
